name: "Build Assets"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'resources/views/**.php'
      - 'resources/js/**.js'
      - 'resources/css/**.css'

jobs:
  assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node
        uses: actions/setup-node@v5

      - name: Install dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Chore: build assets"
          commit_user_name: "GitHub Actions"
